version: '3.9'
services:
  proyecto-monolitico:
    container_name: proyecto-monolitico
    image: proyecto-monolitico:v1
    build:
      context: .
    ports:
      - "4040:4040"
    networks:
      - proyecto-app
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4040
  balanceador:
    container_name: balanceador
    image: balanceador:v1
    build:
      context: ./BalanceadorCarga
    ports:
      - "4003:80"
    networks:
      - proyecto-app

networks:
  proyecto-app:

